### ISSUE TITLE
为什么离顶部有一段距离

### ISSUE THREAD

**Issue by itsgm** [385841539/flutter_BaseWidget#1]
布局默认离顶部有距离

**Comment by 385841539** [comment]
你的效果我看见了， 是你内部控件RaisedButton的距离。

**Comment by xiongwenzhi** [comment]
为什么在BottomNavigationBar  里面的页面 会有空隙

**Comment by 385841539** [comment]
没有吧  ， 我用背景测试过 ， 如果说是底部导航栏 ， 那可以自己看看底部导航栏的 配置

**Comment by xiongwenzhi** [comment]
我底部导航都是默认的，没设置什么特别的东西，我刚刚已经加了你的群661614986   能通过下么

**Comment by 385841539** [comment]
好的 



------------------ 原始邮件 ------------------
发件人: "xiongwenzhi"<notifications@github.com>; 
发送时间: 2019年4月16日(星期二) 下午3:20
收件人: "385841539/flutter_BaseWidget"<flutter_BaseWidget@noreply.github.com>; 
抄送: "眞永遠"<385841539@qq.com>; "Comment"<comment@noreply.github.com>; 
主题: Re: [385841539/flutter_BaseWidget] 为什么离顶部有一段距离 (#1)




我底部导航都是默认的，没设置什么特别的东西，我刚刚已经加了你的群661614986   能通过下么
